#!/bin/bash
#2.3 SEARCH
function search_func () {
if [[ $# -eq 2 ]]
then if [ -z "$1" ]
     then echo "Null dir"
     exit 4
      else if [ -z "$2" ]
           then echo "Null val"
           exit 5
            else if [ -d "$1" ]
                 then grep -r "$2" "$1" 2> /dev/null
                  else exit 3
                  fi
            fi
      fi
 else
 exit 2
 fi
}
