#!/bin/bash
LastDateBackup=$(ls ~ | grep -E "Backup-" | sort -n | tail -1 | sed 's/^Backup-//' )
LastBackup="$HOME/Backup-${LastDateBackup}"
if [[ -z "$LastDateBackup" ]]
   then
       exit 1
   fi
if [[ ! -d ~/restore ]]
   then
       mkdir ~/restore
   else
       rm -r ~/restore
       mkdir ~/restore
   fi
for i in $(ls $LastBackup | grep -E -v "\.[0-9]{4}-[0-9]{2}-[0-9]{2}$")
   do
      cp "$(LastBackup)/$(i)" "$HOME/restore/$(i)"
   done
