#!/bin/bash
d=$(date '+%d.%m.%y_%H:%M:%S')
mkdir ~/test1 && echo "catalog test was created successfully" >> ~/report.tmp && touch ~/test1/$d.tmp
ping -c 1 www.net_nikogo.ru || echo "Error" >> ~/report.tmp
