#!/bin/bash
bef_file="before"
aft_file="after"
ps aux | awk '{print $2" "$11 }' | sort -nk1 | tail -n +2 | head -n -5 > temp.tmp
while read line
do
pid=$(awk '{print $1}' <<< $line)
bytes_file=$(grep "read_bytes" /proc/"$pid"/io | awk '{print $2}')
patch_file=$(awk '{print $2}' <<< $line)
echo $pid" "$patch_file" "$bytes_file >> "$bef_file"
done < temp.tmp
sleep 1m
cat temp.tmp |
while read line
do
pid=$(awk '{print $1}' <<< $line)
aft_mem=$(grep "read_bytes" /proc/"$pid"/io | awk '{print $2}')
patch_file=$(awk -v id="$pid" '{if($1 == id) print $2 }' < "$bef_file" )
bef_mem=$(awk -v id="$pid" '{if($1 == id) print $3}' < "$bef_file")

new=$(echo "$aft_mem - $bef_mem" | bc)
echo $pid" : "$patch_file" : "$new
done | sort -t " : " -nk3 | tail -n 3
